### ISSUE TITLE
ISO_week representation

### ISSUE THREAD

**Issue by glennsl** [daypack-dev/timere#35]
When dealing with weeks, it would be very convenient to be able to store the ISO week and ISO year together, so that operations could be made on these in a strongly typed manner.

I'm not sure how this would fit in with the reasoning capabilities, but some useful operations on a week-level are:

- Generate a sequence of the weeks in some interval, e.g. `["2021W51"; "2021W52"; "2022W01"; "2022W02"]`
- How many weeks there are between `1982W31` and `1984W42`
- Which week is 12 weeks prior to `1999W06`
- Convert to and from the ISO8601 string representation (basic and extended) to use in query parameters and such.

None of these are particularly easy to accomplish currently, I believe. Would you consider, at first, accepting a PR that adds an `ISO_week`  module to `Timedesc`? Then after that perhaps we can discuss how best to implement functionality on top of it.

PS: There is also a need for a similar representation and functionality for months, but I'll hold off on that to gauge your response to this request first.

**Comment by darrenldl** [comment]
> Generate a sequence of the weeks in some interval, e.g. ["2021W51"; "2021W52"; "2022W01"; "2022W02"]

This is already possible to do, but not as convenient as a direct call - one would need to use timestamp as the base unit, and the pretty printer need to be upgraded to support ISO year, week printing.

> How many weeks there are between 1982W31 and 1984W42

I think I avoided something similar due to ambiguity when the base unit is not at second/ns granularity. For instance, how many weeks are between W1 and W2? 0? 1? 2? I.e. do we pick the start of both weeks, or start of W1 but end of W2 and so on.

I don't use week dates enough to know whether this is a legitimate concern though, so I'd be happy to hear more about it.

> Convert to and from the ISO8601 string representation (basic and extended) to use in query parameters and such.

The ISO8601 parser right now ingests week dates I believe, but we do lack a way to emit week date ISO8601 strings.

> PS: There is also a need for a similar representation and functionality for months, but I'll hold off on that to gauge your response to this request first.

Several libraries have tried with month level arithmetic, they have had to settle with necessarily odd design choices due to inconsistent lengths of months. I am not too convince that's a good route unless you've got other ideas. I'll add that time zone complicates the arithmetic further if I recall correctly.

---

Overall I wouldn't mind an upgrade to `ISO_week` and/or `ISO_week_date` module, but I don't want to settle on semantics that do not make sense immediately (or only make perfect sense in a specific context).

**Comment by glennsl** [comment]
> For instance, how many weeks are between W1 and W2? 0? 1? 2? I.e. do we pick the start of both weeks, or start of W1 but end of W2 and so on.

Maybe I'm misunderstanding you, but I don't think reasoning about weeks should consider anything more precise than the week itself. So I'd expect this to work according to the normal arithmetic rules, i.e. `W02 - W01 = 1` and, since week 52 is the last week of 2021, `2022W01 - 2021W52 = 1`.

> The ISO8601 parser right now ingests week dates I believe, but we do lack a way to emit week date ISO8601 strings.

Fortunately that's the easy part :) But it'd also be a good idea to distinguish ISO week dates from ISO weeks, I think, instead of assuming a default weekday if the date part is missing or accepting `2021-W01-7` as an ISO week. I'm not sure how well that would integrate with the current parser though.

> Several libraries have tried with month level arithmetic, they have had to settle with necessarily odd design choices due to inconsistent lengths of months. I am not too convince that's a good route unless you've got other ideas. 

I'm not sure I understand why the length of months would matter. Since there's always 12 months in every year, it should be as simple as incrementing the year when you roll over from December to January, and decrementing the year when going from January back to December.

Perhaps you're thinking of these as being represented by dates or timestamps still, and having to add or subtract a number of days depending on which month you're in, or passing through? If so, that is exactly why I think having these less precise representations will make it much easier to deal with. But perhaps that goes against the philosophy of the library in some way?

**Comment by darrenldl** [comment]
> Maybe I'm misunderstanding you, but I don't think reasoning about weeks should consider anything more precise than the week itself. So I'd expect this to work according to the normal arithmetic rules, i.e. W02 - W01 = 1 and, since week 52 is the last week of 2021, 2022W01 - 2021W52 = 1.

Sure, that translates to gap between start of both weeks, rather than gap between the weeks. If former is the consensus on what it means for "between" then sure, but I don't know if there is such consensus.

Another similar question would be "How many days are between today and tomorrow?", and I would not be surprised if I hear answers from 0 to 1.

> Perhaps you're thinking of these as being represented by dates or timestamps still, and having to add or subtract a number of days depending on which month you're in, or passing through? If so, that is exactly why I think having these less precise representations will make it much easier to deal with. But perhaps that goes against the philosophy of the library in some way?

Well the library was somewhat an answer to lack of precision to dealing with things including time zones in the other libraries, so I don't want to introduce anything that makes things imprecise.

Though I guess if we just drop the requirement of there being any meaning alluding to a duration, then that's fine. (Closing to pattern matching than duration based arithmetic in other words.)

I am still not sure how week and month arithmetic interacts with time zone and DST though.

**Comment by darrenldl** [comment]
To elaborate a bit more - if we do have next n month/week functions and other arithmetic-ish stuff, I feel there will be friction in not allowing those to be used with date times (cause to an average user, it would seem reasonable), but then we'll have ambiguity.

**Comment by darrenldl** [comment]
Rereading the API and rethinking a bit, I think your proposal would work. We already have similar constructions of date time from Date.t and destruction to Date.t, which are explicitly zoneless. So we're just introducing a coarser "date" so to speak.

And yeah, since we'll be adding successor and predecessor functions anyway ("next week"/"next month"), we can just define semantics of of add/sub n and "between" in those terms.

I'll have more time later this week to add those and refactor a bit.

**Comment by glennsl** [comment]
Awesome! Looking forward to see what you come up with. And thanks for being very responsive!

> Sure, that translates to gap between start of both weeks, rather than gap between the weeks. If former is the consensus on what it means for "between" then sure, but I don't know if there is such consensus.

I think that depends on how you express it. If you express it as arithmetic subtraction, it seems pretty unambiguous to me. But if you express it as am operation literally named `between`, I agree it's ambiguous. I think that's mostly because human language is ambiguous though.

**Comment by darrenldl** [comment]
I am thinking of `Partial_date` as the top level module for the `ISO_week` and `Ym` submodules, what do you reckon?

**Comment by glennsl** [comment]
I don't hate it :joy: I'm not sure I understand the purpose though.

What do you mean by "top level"? Would it be`Timedesc.Partial_date`? Or just `Partial_date`, effectively a separate library that you could opt in to? And is it just to be more descriptive, or do you imagine there would be some common functionality?

**Comment by darrenldl** [comment]
Oh sorry, yep `Timedesc.Partial_date`, similar to purpose of `Timedesc.Date`

**Comment by glennsl** [comment]
In that case I think I would expect `Partial_date` to be a stand-alone concept of some kind, similar to `Date`, with `ISO_week` and `Ym` being different views into that. That doesn't seem to really make sense though, so I worry that this might just make it more confusing.

**Comment by darrenldl** [comment]
What do you suggest?

**Comment by glennsl** [comment]
I suppose I would suggest having `ISO_week` and `Ym` be top level modules, as there's no common representation between them. But that's just based on my understanding of what the module hierarchy means, which might of course be wrong.

**Comment by darrenldl** [comment]
Oh yeah true, they don't share a common representation, forgot that's the main point of `view`.

Yeah that makes sense, I'll go with them being directly under Timedesc (so `Timedesc.ISO_week` and `Timedesc.Ym`).

**Comment by darrenldl** [comment]
Tentative design pushed to `dev` branch, what you reckon?

```
(** {2 Partial date}

    Implementation of:
    - Gregorian year month ({!Ym})
    - ISO week ({!ISO_week})
*)

module Ym : sig
  type t

  type error =
    [ `Does_not_exist
    | `Invalid_year of int
    | `Invalid_month of int
    ]

  exception Error_exn of error

  (** {1 Constructors} *)

  val make : year:int -> month:int -> (t, error) result

  val make_exn : year:int -> month:int -> t

  (** {1 Accessors} *)

  val year : t -> int

  val month : t -> int

  val year_month : t -> int * int

  (** {1 Arithmetic} *)

  val add : ?year:int -> ?month:int -> t -> t

  val sub : ?year:int -> ?month:int -> t -> t

  val diff_month : t -> t -> int
end

module ISO_week : sig
  type t

  type error =
    [ `Does_not_exist
    | `Invalid_iso_week_year of int
    | `Invalid_iso_week of int
    ]

  (** {1 Constructors} *)

  val make : iso_week_year:int -> iso_week:int -> (t, error) result

  val make_exn : iso_week_year:int -> iso_week:int -> t

  (** {1 Accessors} *)

  val iso_week_year : t -> int

  val iso_week : t -> int

  val iso_week_year_and_week : t -> int * int

  (** {1 Arithmetic} *)

  val add_week : t -> int -> t

  val sub_week : t -> int -> t

  val diff_week : t -> t -> int
end
```

I'll add ISO8601 printing and parsing shortly, but adding the relevant test suite will take a while...

**Comment by glennsl** [comment]
Looks great. Thank you! I left some comments on the PR, mostly just terminological nits.
